[graph]
all-features = true

[licenses]
allow = [
  "MIT",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "Zlib",
  "Unlicense",
  "Unicode-3.0",
]
exceptions = [
    { allow = ["CDLA-Permissive-2.0"], crate = "webpki-roots" },
]
confidence-threshold = 0.95

[bans]
multiple-versions = "allow"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
